version: 2

steps: &steps
  steps:
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}
    - checkout
    - run:
        name: Install libraries
        command: apt-get update && apt-get install -y --no-install-recommends libhdf5-dev
    - run:
        name: Install package dependencies
        command: R -e "devtools::install_deps(dep = TRUE)"
    - run:
        name: Build package
        command: R CMD build .
    - run:
        name: Check package
        command: R CMD check *tar.gz
    - save_cache:
        key: cache-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/usr/local/lib/R/site-library"

jobs:
  releaseR4.1.0:
    docker:
      - image: rocker/verse:4.1.0
    <<: *steps
  oldR3.5.3:
    docker:
      - image: rocker/verse:3.5.3
    <<: *steps
  develR:
    docker:
      - image: rocker/verse:devel
    <<: *steps

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - releaseR4.1.0:
          filters:
            tags:
              only: /.*/
      #- oldR3.5.3:
      #    filters:
      #      tags:
      #        only: /.*/
      - develR:
          filters:
            tags:
              only: /.*/


