version: 2

steps: &steps
  steps:
    - checkout
    - run:
        name: Install libraries
        command: apt-get update && apt-get install -y --no-install-recommends libhdf5-dev
    - run:
        name: Install libraries for latex
        command: apt-get update && apt-get install -y --no-install-recommends texlive-fonts-recommended
    - run:
        name: Install package dependencies
        command: R -e "devtools::install_deps(dep = TRUE)"
    - run:
        name: Install package dependencies (hdf5r)
        command: R -e "require(hdf5r)" # "lapply(c('hdf5r','HDF5Array','DelayedArray'), require, character.only=TRUE)"
    - run:
        name: Build package
        command: R CMD build .
    - run:
        name: Check package
        command: R CMD check *tar.gz


jobs:
  releaseR4.1.2:
    docker:
      - image: rocker/verse:4.1.2
    <<: *steps
  # releaseR4.2.0:
  #   docker:
  #     - image: rocker/verse:4.2.0
  #   <<: *steps
  develR:
    docker:
      - image: rocker/verse:devel
    <<: *steps

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - releaseR4.1.2:
          filters:
            tags:
              only: /.*/
      # - releaseR4.2.0:
      #     filters:
      #       tags:
      #         only: /.*/
      - develR:
          filters:
            tags:
              only: /.*/


